[package]
name = "chi"
version = "0.1.0"
authors = ["Taylor Sutton <tsutton125@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonpath_lib = "0.2.6"
serde_yaml = "0.8.17"
clap = "2.33.3"
nom = "6.1.2"
thiserror = "1.0.24"

