[package]
name = "chi"
version = "0.1.0"
authors = ["Taylor Sutton <tsutton125@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
